/**
 * seed-flashcards-190.ts
 * Seeds NES 190 vocabulary flashcards.
 * Run: CONFIRM_SEED=true npx tsx scripts/seed-flashcards-190.ts
 */
import dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })
import connectDB from '../lib/mongodb'
import Vocabulary from '../models/Vocabulary'

if (process.env.CONFIRM_SEED !== 'true') {
  console.error('🔴 This will insert/replace NES 190 flashcards.')
  console.error('To proceed: CONFIRM_SEED=true npx tsx scripts/seed-flashcards-190.ts')
  process.exit(1)
}

const flashcards = [
  // ─────────────────────────────────────────────────────────────
  // SUBAREA I — Foundations of Reading Development
  // Objective 1: Phonological & Phonemic Awareness, Concepts of Print, Alphabetic Principle
  // ─────────────────────────────────────────────────────────────
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Phonological awareness',
    definition: 'The broad understanding that spoken language is made up of smaller sound units — words, syllables, and onset-rime patterns. It is a listening and speaking skill; no print is involved.',
    example: 'Clapping syllables in "butterfly" or identifying that "cat" rhymes with "bat."',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Phonemic awareness',
    definition: 'A specific subset of phonological awareness focused exclusively on individual phonemes — the smallest units of sound in spoken language. All tasks are completely oral; the moment print appears, the task becomes phonics.',
    example: 'Segmenting "dog" into /d/ /ɒ/ /g/ or blending /s/ /t/ /ɒ/ /p/ into "stop."',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Phoneme segmentation',
    definition: 'Breaking a spoken word into all of its individual sounds in sequence. It is the single strongest predictor of early reading achievement and a prerequisite for phonics decoding.',
    example: 'Students push a token into each Elkonin box for every sound they hear: "cat" → /k/ /æ/ /t/ = 3 boxes.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Phoneme blending',
    definition: 'Combining isolated phonemes spoken in sequence into a recognizable word. It is an important predictor of decoding success because it mirrors what the brain does when reading phonetically.',
    example: 'Teacher says /d/ /ɒ/ /g/ slowly; students respond "dog."',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Phoneme manipulation',
    definition: 'The most advanced phonemic awareness skill — changing a word by deleting, adding, or substituting a phoneme. These tasks (deletion, addition, substitution) require the student to hold the word in working memory while altering one sound.',
    example: '"Say cat without /k/" → "at" (deletion); "change /b/ in bat to /s/" → "sat" (substitution).',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Onset-rime awareness',
    definition: 'Awareness that each syllable can be divided into an onset (the initial consonant or consonant cluster before the vowel) and a rime (the vowel and everything that follows). Rhyming and word-family tasks operate at this level.',
    example: 'In "bat," the onset is /b/ and the rime is -at; bat, cat, sat, and hat all share the same rime.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Concepts of print',
    definition: 'The understandings about how written language works that children must acquire before or alongside phonics: print carries meaning, English is read left-to-right and top-to-bottom, spaces mark word boundaries, and books have orientation conventions.',
    example: 'During a shared reading, the teacher points word-by-word to demonstrate one-to-one correspondence between spoken and printed words.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Alphabetic principle',
    definition: 'The understanding that letters and letter combinations systematically represent the sounds of spoken language. Once students grasp this concept, they can apply phonics patterns to decode unfamiliar words.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Elkonin (sound) boxes',
    definition: 'A phonemic awareness instructional tool: a row of connected boxes, one per phoneme, where students push a token into each box as they say each sound in a word. Boxes can be extended into phonics by having students write letters instead of using tokens.',
    example: 'A student says "ship" and pushes tokens: one for /ʃ/, one for /ɪ/, one for /p/ — three boxes total.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Invented (phonetic) spelling',
    definition: 'Writing words using known letter-sound knowledge rather than conventional spelling (e.g., "kat" for "cat"). Analyzing invented spellings reveals a student\'s current phonemic awareness and phonics development and simultaneously reinforces both skills.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 1,
    term: 'Dialogic reading',
    definition: 'An interactive read-aloud technique where the teacher prompts children to retell, elaborate, and engage with the text rather than listening passively. It is especially effective for building oral vocabulary and narrative comprehension in young children.',
    isPublished: true,
  },

  // ─────────────────────────────────────────────────────────────
  // Objective 2: Phonics, High-Frequency Words, and Spelling
  // ─────────────────────────────────────────────────────────────
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'Systematic explicit phonics',
    definition: 'Phonics instruction that presents letter-sound relationships in a deliberate scope and sequence from simple (single consonants, short vowels in CVC words) to complex (digraphs, blends, vowel teams, multisyllabic patterns). Research consistently shows this produces better outcomes than embedded or incidental approaches.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'Consonant digraph',
    definition: 'Two consecutive consonants that together represent a single phoneme, with each letter losing its individual sound. Common digraphs include sh, ch, th, wh, ph, ck, and ng.',
    example: 'In "ship," the letters s and h form the digraph sh, representing one sound /ʃ/.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'Consonant blend',
    definition: 'Two or three consonants appearing together where each sound is still pronounced separately. Blends differ from digraphs because all individual sounds remain intact.',
    example: '"str-" in "street" is a blend: /s/, /t/, and /r/ are all pronounced.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'Vowel team',
    definition: 'Two adjacent vowels that together represent a single vowel sound. Often described by the saying "when two vowels go walking, the first one does the talking," though this rule has many exceptions.',
    example: '"ai" in "rain," "ea" in "meat," and "oa" in "boat" are vowel teams.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'Diphthong',
    definition: 'A vowel sound that glides between two positions within a single syllable. Diphthongs are technically distinct from vowel teams because the sound shifts rather than remaining stable.',
    example: '"oi/oy" in "coin" and "boy"; "ou/ow" in "cloud" and "now."',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'R-controlled vowel',
    definition: 'A vowel followed immediately by the letter r, causing the vowel to produce a sound that is neither its short nor its long form. The r modifies the vowel\'s pronunciation.',
    example: '"ar" in "car," "er/ir/ur" in "fern/bird/burn," and "or" in "corn."',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'CVCe (magic e) pattern',
    definition: 'A syllable pattern where a silent final e causes the medial vowel to produce its long sound. One of the earliest multi-letter phonics patterns taught in the scope and sequence.',
    example: '"cake," "bike," "home," and "cute" each follow the CVCe pattern.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'High-frequency words',
    definition: 'Words that appear most often in written text. Many are phonetically irregular and must be memorized as whole words; others are phonetically regular but require automaticity. The Dolch list (220 words) and Fry list (1,000 words) are the two most widely used.',
    example: 'The Fry top 100 words ("the," "of," "and," "a") account for roughly half of all words in written text.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'Homograph',
    definition: 'A word spelled identically to another word but with a different meaning and sometimes a different pronunciation depending on context. Semantic and syntactic context must be used to confirm the correct pronunciation.',
    example: '"Tear" can mean a drop of water (/tɪər/) or to rip (/tɛr/) — only sentence context resolves which meaning applies.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'Word sorts',
    definition: 'A phonics activity where students categorize words by spelling pattern (e.g., CVC vs. CVCe). Closed sorts provide the categories; open sorts let students determine their own. Word sorts build pattern recognition, spelling awareness, and close attention to word structure.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'Decodable text',
    definition: 'Text written specifically to use only phonics patterns that students have already been explicitly taught. It is the appropriate independent practice vehicle for early readers who are consolidating newly learned phonics patterns.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 2,
    term: 'Inflectional morpheme',
    definition: 'A suffix that signals a grammatical relationship without changing a word\'s part of speech. The eight English inflectional morphemes are -s, -es, -ed, -ing, -er (comparative), -est, -\'s, and -s\' (possessives).',
    example: '"Jumped" adds -ed to show past tense; "taller" adds -er to show comparison — both stay adjectives/verbs.',
    isPublished: true,
  },

  // ─────────────────────────────────────────────────────────────
  // Objective 3: Syllabication, Morphemic Analysis, Orthography
  // ─────────────────────────────────────────────────────────────
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Six syllable types',
    definition: 'Every English syllable fits one of six categories: closed (ends in consonant, short vowel), open (ends with vowel, long vowel), vowel-consonant-e (silent e makes vowel long), vowel team (two vowels together), r-controlled (vowel + r), and consonant-le (final consonant + le). Teaching these gives students a reliable system for decoding any multisyllabic word.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Closed syllable',
    definition: 'A syllable that ends in one or more consonants, causing the vowel to be short. It is the most common syllable type in English.',
    example: '"cat," "sit," and the first syllable of "hap-pen" are all closed syllables.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Open syllable',
    definition: 'A syllable that ends with a vowel, causing that vowel to say its long sound. The VC/CV and V/CV syllabication rules help students find open syllables in multisyllabic words.',
    example: '"me," "go," and the first syllable of "ba-by" or "ti-ger" are open syllables.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Derivational morpheme',
    definition: 'A prefix or suffix that creates a new word, often changing its part of speech. Unlike inflectional morphemes, derivational morphemes alter meaning and frequently shift grammatical category.',
    example: '"act" (verb) + -ion → "action" (noun); "happy" (adj) + -ness → "happiness" (noun).',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Free vs. bound morpheme',
    definition: 'A free morpheme can stand alone as a word (play, friend, act). A bound morpheme must attach to another morpheme and cannot stand alone — all prefixes and suffixes are bound morphemes.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Latin and Greek roots',
    definition: 'Core morphemes from Latin or Greek that carry primary meaning and appear in hundreds of English academic words. Knowledge of 20 common roots (port, dict, bio, graph, phon, geo) unlocks vocabulary across subjects.',
    example: 'The root "port" (carry) appears in transport, import, export, portable, and portable.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Morpheme analysis',
    definition: 'A vocabulary and decoding strategy in which students decompose an unfamiliar word into its meaningful parts (prefix + root + suffix) to infer its meaning. Morpheme analysis scales vocabulary learning efficiently across content areas.',
    example: 'Seeing "biosphere" for the first time, a student uses bio (life) + sphere (globe) to infer "the zone of life surrounding Earth."',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Orthographic rules',
    definition: 'Spelling patterns that govern how words change when suffixes are added. The three core rules are: drop the silent e before a vowel suffix (make → making), double the final consonant in a CVC word before a vowel suffix (hop → hopping), and change y to i before most suffixes (happy → happiness).',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Cognate awareness instruction',
    definition: 'Explicitly teaching English learners to recognize words that share the same Latin or Greek root in both English and their home language. Spanish, French, and other Romance languages share thousands of cognates with English academic vocabulary, making this a powerful vocabulary strategy for EL students.',
    example: 'A Spanish speaker recognizes that "nation" and "nación" share meaning, unlocking related words like "national" and "nationality."',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 3,
    term: 'Syllabication strategies (VC/CV, V/CV)',
    definition: 'Rules for dividing multisyllabic words into syllables. The VC/CV rule splits between two consonants (hap-pen); the V/CV rule tries splitting before the single consonant to attempt an open syllable first (ti-ger). Students identify the syllable type of each part and blend.',
    isPublished: true,
  },

  // ─────────────────────────────────────────────────────────────
  // Objective 4: Reading Fluency
  // ─────────────────────────────────────────────────────────────
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: 'Reading fluency',
    definition: 'Reading connected text with three integrated components: accuracy (decoding words correctly), rate (reading at an appropriate pace), and prosody (reading with expression and phrasing that reflects meaning). All three are required — a fast but monotone reader is not yet fully fluent.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: 'Prosody',
    definition: 'The component of fluency involving reading with appropriate expression, phrasing, intonation, and rhythm that reflects the meaning of the text. Prosody is the bridge between fluency and comprehension — a reader with good prosody is constructing meaning, not just recognizing words.',
    example: 'A student reading "Was she really going to jump?" with rising intonation demonstrates prosodic understanding of the question.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: 'Automaticity',
    definition: 'Fast, effortless word recognition that requires minimal conscious attention. When decoding is automatic, cognitive resources are freed for comprehension. Automaticity develops through wide, repeated reading at the independent level.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: 'WCPM (words correct per minute)',
    definition: 'The standard metric for oral reading fluency — the number of words read correctly during a timed one-minute oral reading. Errors reduce the count. WCPM is compared to grade-level benchmarks to identify students below benchmark.',
    example: 'A student reads a 100-word passage in one minute with 6 errors; WCPM = 94.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: 'Independent reading level',
    definition: 'The text difficulty level at which a student reads with 95% or higher accuracy and full comprehension without support. Wide reading at the independent level is the primary vehicle for building automaticity over time.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: 'Instructional reading level',
    definition: 'The text difficulty level at which a student reads with 90–94% accuracy and needs some teacher support to comprehend. This is the appropriate level for guided reading instruction.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: 'Repeated reading',
    definition: 'The most research-supported fluency intervention: students read the same passage multiple times, with a fluent model first, aiming to improve rate and prosody. Most effective when text is at the instructional level and corrective feedback is provided after each reading.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: 'Echo reading',
    definition: 'A fluency instructional technique where the teacher reads a phrase or sentence aloud and students immediately repeat it, mimicking the teacher\'s phrasing and expression. Provides a fluent model and immediate prosody practice.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: 'Phrase-cued reading',
    definition: 'Text is marked with slash marks at natural phrase boundaries so students pause at meaningful chunks rather than word by word. Directly develops prosody by teaching syntactically appropriate phrasing.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'I',
    subareaName: 'Foundations of Reading Development',
    objectiveNumber: 4,
    term: "Reader's Theater",
    definition: 'Students rehearse and perform scripts adapted from books, reading their assigned parts aloud for an audience. The authentic motivation to perform drives repeated reading and builds fluency, prosody, and engagement simultaneously.',
    isPublished: true,
  },

  // ─────────────────────────────────────────────────────────────
  // SUBAREA II — Development of Reading Comprehension
  // Objective 5: Vocabulary and Academic Language Development
  // ─────────────────────────────────────────────────────────────
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 5,
    term: "Beck's three-tier vocabulary model",
    definition: 'A framework for classifying and prioritizing vocabulary instruction. Tier 1 words are basic conversational words most students already know. Tier 2 words are high-frequency academic words used across many subjects and rarely defined in context. Tier 3 words are low-frequency, domain-specific technical terms.',
    example: '"Dog" = Tier 1; "analyze" = Tier 2; "photosynthesis" = Tier 3.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 5,
    term: 'Tier 2 vocabulary',
    definition: 'High-utility academic words that appear across many subjects and texts but are rarely defined in context and are not basic conversational words. These are the highest instructional priority for direct vocabulary teaching because they significantly affect comprehension in every content area.',
    example: 'Words like "analyze," "significant," "contrast," "evidence," "perspective," and "establish."',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 5,
    term: 'Context clue types',
    definition: 'Textual signals that authors embed to help readers understand unfamiliar words. The five main types are definition/explanation (author directly defines), apposition (definition set off by commas or dashes), restatement/synonym (similar word nearby), contrast/antonym (opposite meaning), and syntax/grammar (the word\'s grammatical role).',
    example: '"The entomologist, a scientist who studies insects, examined the specimen" uses apposition to define the word.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 5,
    term: 'Direct vocabulary instruction',
    definition: 'Explicitly teaching specific target words before or during reading using student-friendly definitions, multiple contextualized examples, and student-practice opportunities. The most reliable method for ensuring students learn particular words.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 5,
    term: 'Semantic mapping',
    definition: 'A visual vocabulary strategy where students build a web around a target word, connecting synonyms, antonyms, examples, non-examples, and related concepts. Builds deep, networked word knowledge rather than surface-level definition memorization.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 5,
    term: 'Word consciousness',
    definition: 'Students\' interest in, and awareness of, words — noticing new words in context, appreciating authors\' word choices, and enjoying wordplay and etymology. Teachers build it by celebrating interesting word choices and encouraging students to collect new words.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 5,
    term: 'Academic language',
    definition: 'The language of school and text — including Tier 2 vocabulary, complex sentence structures (passive voice, embedded clauses), idioms, discipline-specific word meanings, and discourse patterns of academic genres. Academic language differs significantly from conversational English and requires explicit instruction.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 5,
    term: 'Idioms',
    definition: 'Fixed expressions whose meaning cannot be inferred from the literal meanings of the individual words. Idioms are especially challenging for English learners and literal thinkers, and require explicit instruction in academic language development.',
    example: '"Raining cats and dogs," "hit the nail on the head," and "under the weather" are common English idioms.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 5,
    term: 'Wide reading for vocabulary',
    definition: 'Research shows that most vocabulary is acquired incidentally through reading large volumes of varied text. Students who read broadly across genres and topics encounter new words repeatedly in varied contexts, building durable word knowledge over time.',
    isPublished: true,
  },

  // ─────────────────────────────────────────────────────────────
  // Objective 6: Literary Text Comprehension
  // ─────────────────────────────────────────────────────────────
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Three levels of reading comprehension',
    definition: 'Literal comprehension is understanding information explicitly stated in the text. Inferential comprehension requires reading between the lines to draw conclusions from textual clues and background knowledge. Evaluative (critical) comprehension involves making judgments about the author\'s craft, perspective, or argument.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Story grammar',
    definition: 'The structural elements common to narratives: characters, setting, problem/conflict, rising action/events, climax, resolution, and theme. Students who can identify and retell all elements demonstrate understanding of narrative text structure.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Theme vs. topic',
    definition: 'Topic is what a story is about (a boy overcoming fear); theme is the insight about life or human nature that the story conveys ("Courage means doing something even when you are afraid"). Students often confuse the two: theme must be expressed as a full statement, not a single word.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Point of view in narrative',
    definition: 'The perspective from which a story is told. First person means the narrator is a character (limited to one perspective). Third-person limited means the narrator sees one character\'s inner thoughts. Third-person omniscient means the narrator can access all characters\' thoughts and feelings.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Figurative language',
    definition: 'Language that conveys meaning beyond the literal definition of the words. Key types include simile (comparison using like/as), metaphor (direct comparison), personification (human qualities given to nonhuman things), hyperbole (extreme exaggeration), alliteration, and onomatopoeia.',
    example: '"The wind whispered through the trees" uses personification.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Aesthetic vs. efferent reading',
    definition: 'Rosenblatt\'s transactional theory distinguishes two reading stances. Aesthetic reading focuses on the lived-through experience of the text — the feelings and images it evokes — and is most appropriate for literary texts. Efferent reading focuses on extracting and taking away specific information, and is most appropriate for informational texts.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Reciprocal teaching',
    definition: 'A structured small-group comprehension strategy where students take turns leading four strategies: predicting (what will happen next), questioning (generating questions about the text), clarifying (resolving confusion), and summarizing (restating the main idea). Research shows significant comprehension gains, especially for struggling readers.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Think-aloud strategy',
    definition: 'The teacher reads aloud and verbalizes the internal comprehension process, making invisible strategies visible and teachable. Students then practice their own think-alouds with peers to develop metacognitive monitoring of their reading.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Close reading',
    definition: 'A disciplined instructional practice where students read short, complex texts multiple times, each reading for a different purpose: first for general understanding, then for vocabulary, then for structure and craft. Text-dependent questions require students to return to specific passages for evidence.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 6,
    term: 'Literature circles',
    definition: 'Small groups that read the same text and meet to discuss using assigned roles (discussion director, literary luminary, connector, illustrator). Develops higher-order thinking, oral language, and the ability to support claims with textual evidence.',
    isPublished: true,
  },

  // ─────────────────────────────────────────────────────────────
  // Objective 7: Informational Text Comprehension
  // ─────────────────────────────────────────────────────────────
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: 'Five informational text structures',
    definition: 'The five organizational patterns of expository text: description (attributes of a topic), sequence/chronological (time order), compare and contrast (similarities and differences), cause and effect (one event causes another), and problem and solution. Teaching text structure improves comprehension by helping readers anticipate how information will unfold.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: 'Signal words',
    definition: 'Transitional words and phrases that indicate the organizational structure of informational text. Students use signal words to identify text structure and organize their comprehension. Each structure has characteristic signals (e.g., "therefore" and "as a result" signal cause-effect; "however" and "in contrast" signal compare-contrast).',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: 'Informational text features',
    definition: 'Non-prose elements in informational texts — headings/subheadings, bold print, captions, tables, charts, diagrams, indexes, glossaries, and hyperlinks — that carry meaning and must be read actively. Students must learn that text features often contain information not in the main text.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: "Author's purpose",
    definition: 'The reason an author wrote a particular text — to inform, persuade, entertain, or explain. Identifying author\'s purpose is an evaluative comprehension skill essential for critically evaluating the reliability and completeness of informational text.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: 'Primary vs. secondary sources',
    definition: 'A primary source is created by someone with direct experience of an event (a diary, letter, photograph, or original research article). A secondary source interprets or analyzes primary sources (a textbook, biography, or review article). Distinguishing them is a core disciplinary literacy skill.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: 'Disciplinary literacy',
    definition: 'The recognition that reading in science, history, and mathematics requires discipline-specific skills and habits of mind that differ from general reading. It includes evaluating sources, understanding discipline-specific word meanings, and using the conventions of each field.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: 'KWL chart',
    definition: 'A pre-reading and post-reading graphic organizer with three columns: what students Know, what they Want to find out, and what they Learned. The K and W columns explicitly activate and organize prior knowledge before reading, creating a cognitive framework that aids comprehension.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: 'Accountable talk',
    definition: 'A set of discussion norms requiring students to support all claims with specific textual evidence ("I agree with ___ because the text says..."). Accountable talk builds the comprehension habit of returning to the text rather than relying on background knowledge or opinion.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: 'Activating schema',
    definition: 'A pre-reading strategy that prompts students to connect what they already know about a topic to the text they are about to read, building a mental framework that aids comprehension. Activating schema draws on existing knowledge; background knowledge building provides new information — both support comprehension.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'II',
    subareaName: 'Development of Reading Comprehension',
    objectiveNumber: 7,
    term: 'Discipline-specific word meanings',
    definition: 'Many words carry different meanings in different academic subjects. Students must learn these context-dependent meanings explicitly to avoid comprehension errors in content-area reading.',
    example: '"Factor" means a cause in general language but a number that divides evenly in math; "power" means authority in social studies but an exponent or energy rate in science.',
    isPublished: true,
  },

  // ─────────────────────────────────────────────────────────────
  // SUBAREA III — Reading Assessment and Instruction
  // Objective 8: Assessing Reading Development
  // ─────────────────────────────────────────────────────────────
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Screening assessment',
    definition: 'A brief, efficient assessment given universally to all students at the start of the year to identify those who may be at risk and need closer monitoring or intervention. Screening tells you who — not why. A diagnostic assessment is needed to determine what specific skills are weak.',
    example: 'DIBELS, AIMSWEB, and easyCBM are widely used universal screening tools.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Diagnostic assessment',
    definition: 'An in-depth assessment given after screening to identify precisely which specific skills a struggling student has and has not mastered. Diagnostic assessments answer the question "why is this student struggling?" and directly inform targeted intervention planning.',
    example: 'CORE Phonics Survey, Qualitative Reading Inventory (QRI), and spelling inventories are diagnostic tools.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Progress monitoring',
    definition: 'Frequent (weekly or biweekly) assessment given to students receiving intervention to determine whether the intervention is working and whether instructional adjustments are needed. It differs from screening in that it is targeted (not universal) and ongoing.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Curriculum-based measurement (CBM)',
    definition: 'A type of progress monitoring using brief, standardized probes drawn from the curriculum — such as one-minute oral reading passages or nonsense word fluency tasks. CBM is highly sensitive to growth over short periods, making it ideal for tracking intervention effectiveness.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Running record',
    definition: 'An informal, teacher-administered assessment where the teacher records every word a student reads aloud, noting errors, self-corrections, and reading behaviors. A running record yields accuracy percentage, error types, and reading strategies used — a rich diagnostic window into a reader\'s process.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Validity and reliability',
    definition: 'Validity means an assessment actually measures what it claims to measure. Reliability means it produces consistent results across administrations and scorers. An assessment can be reliable but invalid (consistently measuring the wrong thing); it cannot be valid if it is unreliable.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Criterion-referenced assessment',
    definition: 'An assessment that compares a student\'s performance to a fixed standard or benchmark rather than to peers. It tells you whether the student has reached a specific goal, not how they rank compared to others.',
    example: 'A spring second-grade WCPM benchmark of 95 is a criterion-referenced standard.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Norm-referenced assessment',
    definition: 'An assessment that compares a student\'s performance to a representative sample of same-age or same-grade peers. Results are reported as percentile ranks or standard scores. Tells you how the student compares to peers — not whether they have mastered a specific skill.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Assessment of EL students',
    definition: 'English learners\' reading difficulties may stem from limited English oral language proficiency rather than a reading disability. Assessing oral language proficiency in English separately from reading skills prevents over-identification and ensures intervention is matched to the correct underlying cause.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 8,
    term: 'Flexible grouping based on data',
    definition: 'Forming small instructional groups based on current assessment data and adjusting group membership as student performance changes. Flexible grouping prevents the permanent ability labels that inhibit growth, allowing students to move to more advanced groups as their skills develop.',
    isPublished: true,
  },

  // ─────────────────────────────────────────────────────────────
  // Objective 9: Evidence-Based Reading Instruction
  // ─────────────────────────────────────────────────────────────
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: 'Simple View of Reading',
    definition: 'Gough and Tunmer\'s foundational formula: Reading Comprehension = Decoding x Language Comprehension. If either component is zero, reading comprehension is zero. The formula guides diagnosis — identifying which factor (or both) is limiting a student\'s reading.',
    example: 'A student who decodes accurately but comprehends poorly has a language comprehension deficit, not a phonics problem.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: "Ehri's phases of word reading",
    definition: 'A developmental model with four overlapping phases: Pre-Alphabetic (visual/contextual cues only), Partial Alphabetic (first and last letters only), Full Alphabetic (complete letter-sound mappings, accurate but slow), and Consolidated Alphabetic (letter patterns and morphemes recognized as units — fast and automatic).',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: 'Five components of reading',
    definition: 'The National Reading Panel identified five essential components of effective reading instruction: phonemic awareness, phonics, fluency, vocabulary, and text comprehension. All five must be addressed for students to become proficient readers.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: 'MTSS (Multi-Tiered Systems of Support)',
    definition: 'A school-wide framework for organizing reading instruction and intervention across three tiers. Tier 1 is high-quality core instruction for all students. Tier 2 is small-group supplemental intervention for students below benchmark. Tier 3 is intensive, individualized intervention for students significantly below benchmark or non-responsive to Tier 2.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: 'Text complexity: three dimensions',
    definition: 'The Common Core framework defines text complexity using three dimensions that must all be considered: quantitative (measurable factors like Lexile level, sentence length), qualitative (human-judgment factors like meaning complexity, language conventionality, knowledge demands), and reader-and-task considerations (the reader\'s motivation, prior knowledge, and the purpose of the reading task).',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: 'Text-dependent questions',
    definition: 'Questions that can only be answered by returning to the text — not by drawing on prior knowledge or opinion alone. Text-dependent questions are the core of close reading and require students to locate and interpret specific evidence rather than making general inferences.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: 'Integrated literacy model',
    definition: 'An approach to reading instruction that treats reading, writing, speaking, listening, and language as interconnected and mutually reinforcing rather than as separate subjects. A lesson that connects a reading text to a writing response and a vocabulary study produces deeper learning than reading instruction in isolation.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: 'Matthew effect in reading',
    definition: 'The widening gap in reading achievement where skilled readers read more, building vocabulary and background knowledge, while struggling readers read less and fall progressively further behind over time. Named after the biblical verse "the rich get richer."',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: 'Scaffolded instruction',
    definition: 'Temporary, targeted supports (graphic organizers, pre-taught vocabulary, think-alouds, partner structures) that allow students to access grade-level text and work toward independence. Scaffolds are always temporary — the goal is gradual release to independent application. Permanently simplified texts are not scaffolding.',
    isPublished: true,
  },
  {
    examCode: '190',
    subarea: 'III',
    subareaName: 'Reading Assessment and Instruction',
    objectiveNumber: 9,
    term: 'Reading motivation and self-efficacy',
    definition: 'Students who believe they can read (self-efficacy) and who have choice and access to interesting texts read more, which builds skill. Evidence-based motivation strategies include student choice in reading materials, diverse classroom libraries, structured independent reading time, and teacher modeling of reading as a valued activity.',
    isPublished: true,
  },
]

async function main() {
  await connectDB()
  // Delete existing 190 flashcards then insert fresh
  const deleted = await Vocabulary.deleteMany({ examCode: '190' })
  console.log(`Deleted ${deleted.deletedCount} existing cards.`)
  const inserted = await Vocabulary.insertMany(flashcards)
  console.log(`✅ Inserted ${inserted.length} flashcards for NES 190`)
  process.exit(0)
}

main().catch(e => { console.error(e); process.exit(1) })
